development:
  adapter: mysql2
  encoding: utf8
  database: agent_signals_development
  pool: 15
  username: root
  password: mysqlsux!
  reconnect: true

test:
  adapter: mysql2
  encoding: utf8
  database: agent_signals_test
  pool: 15
  username: root
  password: mysqlsux!
  reconnect: true